### PR TITLE
Add `WithLabels` option; Make `GetContainerId` public

### PR DESCRIPTION
**Pull request by bajelidze**
Hi. With this PR I propose two small additions to the project:

#### New `WithLabels` option.
The new `WithLabels` option allows the users to specify labels, i.e., metadata of key-value pairs, that will be applied to the created Localstack container. Labels allow to mark the created Docker containers with useful information that can be used outside of `go-localstack` to manage the created containers.

For example, in my case I want to mark the containers with `expiry` label that will declare when the container is considered expired. I have a running process that every 5 seconds checks the existing containers and removes the expired ones. This way, if my code that uses `go-localstack` panics, I can be sure that another process will take care of the created containers and they won't stay running forever.

#### `GetContainerId` is public now.
The method `GetContainerId` is now public and users of `go-localstack` can use it to retrieve the created container's ID. This maybe useful in scenarios where the users want to manage the created container directly, without `go-localstack`.

If you disagree with making `GetContainerId` public, I think we can revert it back to private. I personally needed `GetContainerId` for the `WithLabels` test I wrote.

### CODE REVIEW

**Comment by elgohr** [comment]
Sorry for the delay. Just saw this. Will have a look

**Comment by elgohr** [comment]
I guess I got the idea. In the past I also found it annoying if containers kept running forever because of panics in tests.
Maybe we could adapt this a little. I was thinking about starting an additional "terminator"-container, which sleeps for a timeout and kills the congestive afterwards (if still present).
Or is there an additional usecase for the metadata?

**Comment by bajelidze** [comment]
Terminator container is an interesting idea and I think it can definitely work. The only problem I see is that for each created Localstack instance, you have to create a terminator container.

In my case, I have multiple tests and I create a Localstack instance for every single one of them. Each test is supposed to run some N minutes and if it doesn't terminate by then, some cleanup mechanism needs to delete the container (even if the test panicked or its process was killed). The terminator container would work here, however if I was to run 100 tests concurrently, I would have 100 terminator containers, so 200 containers in total. I don't think it's a big deal to have extra 100 containers since they will be sleeping most of the time, but creating and deleting them is an extra overhead that adds up when you run keep running these tests.

Metadata may also have other use cases. For example, you may label the created containers by the name of the test that this container is created for. So if I have a test (say a bash script) `test_create_stack.sh`, I could create a Localstack container and label it with `Name=test_create_stack`. And later it's easy to query why the container exists with `docker inspect`.

The only disadvantage of the labeling approach for the cleanup mechanism is that the user has to utilize the labels and create this cleanup logic themselves. With your approach, I guess this would be a part of the `go-localstack` itself and there would be just an option, like `WithLifetime`. So that's why I think we could implement the terminator container logic as well (I guess that would be a separate PR), however, in my case labeling feels more appropriate.

**Comment by elgohr** [comment]
I guess we could have both.
I’m thinking about wrapping the entrypoint with a timeout like this https://stackoverflow.com/a/62663579
Will try to have get this merged tomorrow

**Comment by elgohr** [comment]
Thank you for the PR!
I cherry picked the commit and reverted GetContainerId (as this could be tested differently).
https://github.com/elgohr/go-localstack/commit/8113875617187e1ef43069827cbe53c279906532

**Comment by elgohr** [comment]
@bajelidze containers have a timebomb now https://github.com/elgohr/go-localstack/commit/e68aac2a7d7e89971ba757eadcdc29431e222e21

**Comment by bajelidze** [comment]
@elgohr That's great, thanks! I'll check it out

**Pull request closed without merging**
