### PR TITLE
Add WithRegistry option

### PR DESCRIPTION
**Pull request by bdandy**
Because of DockerHub limits sometimes we need to set our own registry to download localstack.

### CODE REVIEW

**Comment by elgohr** [comment]
Hi, thank you for the PR. Could you please provide tests?

**Comment by elgohr** [comment]
@bdandy ping

**Comment by bdandy** [comment]
It seems like changes were added to build image instead of fetching it, so MR won't work anymore

**Comment by elgohr** [comment]
So we can close this here?

**Comment by bdandy** [comment]
It seems like with new code it's not possible to choose a registry to build the docker container from (for example gitlab proxy), like it was before. 

I'm not sure why it was changed to build container instead of pull.

Anyway this can be closed

**Pull request closed without merging**
