### PR TITLE
add localstack version option, adapt behaviour based on version

### PR DESCRIPTION
**Pull request by hugowetterberg**
Localstack had a breaking change made in v0.11.5 where all services
are exposed through the same port, see
https://github.com/localstack/localstack/blob/master/CHANGELOG.md.

If the caller doesn't specify a version (preserves behaviour to use
"latest") or specifies a version that's v0.11.5 or higher and the port
for all services will resolve to 4566/tcp. Otherwise the old port
mappings will be used.

The configuration is made using a variadic option function argument to
NewInstance() so that it doesn't break API compatability.

```
localstack.NewInstance(localstack.WithVersion("v0.11.5"))
```

New dependency for version parsing and constraints:
github.com/Masterminds/semver/v3

As I added a new dependency I also ran `go mod tidy` which resulted in
a lot of go.sum entries for old (unused) versions of the aws-sdk being
removed.

### CODE REVIEW

**Comment by elgohr** [comment]
Would like to add a few changes.

As I had no push access to your fork, you might want to cherry-pick 
https://github.com/elgohr/go-localstack/commit/9196522fc623ec1fef19ccb18c84fca9a752eff6
https://github.com/elgohr/go-localstack/commit/286d0380aa5a0bf2cb0fdfafaae27fccbcd82130

**Comment by hugowetterberg** [comment]
Of course. I notice that you mix stdlib and third party imports, and overall the grouping and sorting imports is different from what I’m used to. It’s your project and therefore up to you to decide, but do you run goimports on save?

**Comment by elgohr** [comment]
Hey, I don't use goimports at the moment

**Comment by hugowetterberg** [comment]
Ok, no worries, it's outside the scope of this PR, but I really recommend it :)

I cherry-picked your commits, so we should be good to go.

**Comment by elgohr** [comment]
Thank you very much 👍

**Pull request merged**
